CREATE TABLE `cross_validation_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`station_code` varchar(64) NOT NULL,
	`province` varchar(100),
	`constituency` varchar(10),
	`district` varchar(100),
	`ss511_result_id` int,
	`ss518_result_id` int,
	`is_match` boolean DEFAULT false,
	`overall_confidence` int DEFAULT 0,
	`discrepancies` json,
	`candidate_matches` json,
	`summary` text,
	`severity` enum('low','medium','high','critical') DEFAULT 'medium',
	`is_resolved` boolean DEFAULT false,
	`resolved_by` varchar(64),
	`resolved_at` timestamp,
	`resolved_note` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cross_validation_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ocr_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`station_code` varchar(64),
	`province` varchar(100),
	`constituency` varchar(10),
	`district` varchar(100),
	`document_type` enum('ss5_11','ss5_18','unknown') DEFAULT 'unknown',
	`scoring_method` enum('tally','numeric','mixed') DEFAULT 'numeric',
	`provider` varchar(32),
	`total_voters` int,
	`total_ballots` int,
	`spoiled_ballots` int DEFAULT 0,
	`votes_data` json,
	`raw_text` text,
	`confidence` int DEFAULT 0,
	`image_url` varchar(512),
	`image_key` varchar(256),
	`uploaded_by` varchar(64),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ocr_results_id` PRIMARY KEY(`id`)
);
